### ISSUE TITLE
get_serial_number - backport from other repo

### ISSUE THREAD

**Issue by tgreiser** [Wickedlasers/laserdocklib#15]
Currently this version of laserdocklib is missing functionality such as get_serial_number. Could use that information in the TouchDesigner driver in order to show the connected devices by serial number.

See:
https://github.com/Wickedlasers/libLaserdockCore/blob/be8d7b5093f94b476c5f1d02bfaeb1cffd5f7c75/3rdparty/laserdocklib/src/LaserdockDevice.cpp#L425

Related Issue: https://github.com/Wickedlasers/Laser_OS_TouchDesigner/issues/17

**Comment by paulmainwaring** [comment]
@tgreiser Can you elaborate on why you think the get_serial_number is not working? 
This function retrieves the serial number from the usb descriptor and returns it.  
The USB device info for a laser dock device on macOS is shown below:

Laserdock.:

  Product ID:	0x04d8
  Vendor ID:	0x1fc9  (NXP Semiconductors)
  Version:	1.00
  Serial Number:	2191717100001435
  Speed:	Up to 12 Mb/s
  Manufacturer:	WICKED
  Location ID:	0x02100000 / 1
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

The string returned by the get_serial_number function is "2191717100001435" which matches the descriptor info shown above.

**Comment by paulmainwaring** [comment]
@tgreiser Thanks for the update.  We will look into adding this missing feature.

**Comment by paulmainwaring** [comment]
get serial number now added to the library
